application: lime-time
version: 5
runtime: python27
api_version: 1
threadsafe: no

libraries:
- name: django
  version: "1.2"

handlers:
- url: /build
  static_dir: static/build

- url: /i18n/locale?(.*)
  static_files: static/locale.json
  upload: static/locale.json

- url: /ajaxcalls/(.*)
  script: main.py

- url: /oauth/start(.*)
  script: main.py

- url: /imapoauth_step(.*)
  script: main.py
