application: lime-time
version: 6
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: django
  version: "latest"
- name: webapp2
  version: "latest"
- name: pycrypto
  version: "latest"
handlers:
- url: /build
  static_dir: static/build

- url: /i18n/locale?(.*)
  static_files: static/locale.json
  upload: static/locale.json

- url: /worker/(.*)
  script: main.app

- url: /ajaxcalls/(.*)
  script: main.app

- url: /oauth/(.*)
  script: oauth.app

