application: lime-time
version: 4
runtime: python
api_version: 1

handlers:
- url: /build
  static_dir: static/build

- url: /i18n/locale?(.*)
  static_files: static/locale.json
  upload: static/locale.json

- url: /ajaxcalls/(.*)
  script: main.py
